# Generated by Django 4.2.16 on 2025-03-15 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('area', models.FloatField(help_text='Area in acres')),
                ('farm_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('motor_type', models.CharField(max_length=50)),
                ('horsepower', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('installed_date', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('valve_type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('flow_rate', models.IntegerField(blank=True, null=True)),
                ('connection_details', models.CharField(blank=True, max_length=200)),
                ('installed_date', models.DateField()),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='farm.motor')),
            ],
        ),
    ]
